"""add talk cut columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-01 19:32:36.568093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('raw_duration_seconds', sa.Float(), nullable=True))
    op.add_column('talks', sa.Column('cut_start', sa.Float(), nullable=True))
    op.add_column('talks', sa.Column('cut_end', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talks', 'cut_end')
    op.drop_column('talks', 'cut_start')
    op.drop_column('talks', 'raw_duration_seconds')
    # ### end Alembic commands ###
