"""add_user_session_revoked_at

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-07 17:03:19.644336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, Sequence[str], None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_revoked_at', sa.DateTime(timezone=True), server_default=sa.text("'1970-01-01 00:00:00+00'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_revoked_at')
    # ### end Alembic commands ###
